"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = ['assets']
OPTIONS = {
    'packages':['tkinter','customtkinter','rembg','PIL'],
    'iconfile': './assets/icon.png',
    'plist':{
        'CFBundle Development Region': 'English',
        'CFBundle Identifier': "com.royaldevops.removebackground",
        'CFBundleVersion': "1.0.0",
        'NSHumanReadable Copyright': u"Copyright © 2023, Remove Background, All Rights Reserved"
    }
}

setup(
    app=APP,
    name='RemoveBackground',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
